"""Checks FastDNA's three *approximate* answers against the exact one, and
against the reference implementation, on real sequencing data.

Counting is exact, and `kmc3_equivalence.py` already pins it against KMC3.
Everything in this file is deliberately NOT exact -- HyperLogLog, an
ntCard-style sketch, a fitted mixture model -- and each one ships with a
stated error bound. A stated bound that nothing measures is a promise, not a
property, and the suite as it stands measures all three only against
synthetic input:

  * `test_cardinality.py` asserts a relative error < 0.5 against a hand-built
    set (the real rigour lives in `src/hll.rs`'s own tests, against a
    `HashSet` over generated values).
  * `test_spectrum_estimate.py` says in its own docstring that it tests the
    FFI wiring, not the estimate.
  * `test_genomescope.py` fits a spectrum generated by the same family of
    model it then fits, and its only end-to-end assertion accepts anything
    between 2,500 and 10,000 bp on a synthetic 5 kb "genome".

None of those can fail for the reason that matters: being wrong on a real
sequencing run, whose error tail, coverage variance and repeat content no
generator reproduces.

What this asserts, and against what:

  cardinality  HyperLogLog vs the EXACT distinct count from a full count of
               the same file. Ground truth is internal but independently
               corroborated: `kmc3_equivalence.py` shows the same counts are
               KMC3's, to the digit.
  spectrum     ntCard-style streaming estimate vs the EXACT histogram, at
               the low depths where the error peak lives and the estimate is
               hardest.
  genome size  `fastdna.genomescope.profile_genome` vs the real GenomeScope2
               (pinned biocontainer) on the same histogram -- and both
               against a species whose genome size is published.

Usage:

    python scripts/validation/estimator_accuracy.py
    python scripts/validation/estimator_accuracy.py --file reads.fastq.gz --k 21
    python scripts/validation/estimator_accuracy.py --skip-genomescope   # no Docker

Requires a release build (`cargo build --release`) and, unless
`--skip-genomescope`, Docker. Exits non-zero if any estimator misses its own
documented bound.

CAVEAT, stated rather than buried: the default run is E. coli, which is
HAPLOID, while `profile_genome` requires `ploidy=2` and GenomeScope2 is run
with `-p 2`. Both tools are therefore outside their design assumption in the
same way, which makes them comparable to each other and makes the near-zero
heterozygosity both report the expected answer rather than a finding. A
diploid cohort with a published genome size would test more of the model;
this tests the size estimate, which is what the module's headline claim is.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GENOMESCOPE_IMAGE = "quay.io/biocontainers/genomescope2:2.0.1--py313r44hdfd78af_1"

DEFAULT_URL = (
    "https://ftp.sra.ebi.ac.uk/vol1/fastq/DRR002/DRR002015/DRR002015_1.fastq.gz"
)

#: Escherichia coli K-12 MG1655 (NC_000913.3), the species' reference
#: assembly. DRR002015 is strain 2W14, not MG1655, and E. coli genome size
#: genuinely varies by strain (~4.5-5.5 Mb), so this is a plausibility
#: envelope, not a target to hit exactly. A tool that answers 400 kb or
#: 40 Mb is broken; one that answers 4.4 Mb is not.
ECOLI_REFERENCE_BP = 4_641_652
ECOLI_PLAUSIBLE_BP = (4_000_000, 6_000_000)

#: Documented in `estimate_cardinality`'s own docstring as ~0.8% standard
#: error at precision=14. Asserted at 3 sigma so a passing run means the
#: estimator is behaving, not that the bound is loose.
HLL_TOLERANCE_PCT = 2.4


def die(message: str) -> None:
    print(f"\nFAIL: {message}", file=sys.stderr)
    raise SystemExit(1)


def count_exact(binary: Path, reads: Path, k: int, workdir: Path):
    """The ground truth every check below is measured against."""
    out = workdir / f"exact_k{k}.parquet"
    hist = workdir / f"exact_k{k}.hist.csv"
    proc = subprocess.run(
        [str(binary), "--input", str(reads), "--output", str(out),
         "--qc", str(workdir / "qc.json"), "--histogram", str(hist),
         "-k", str(k), "-q", "0", "-m", "1"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        die(f"fastdna exited {proc.returncode}:\n{proc.stderr[-2000:]}")
    distinct = int(re.search(r"Distinct k-mers:\s*(\d+)", proc.stdout).group(1))
    spectrum = {}
    with hist.open() as fh:
        for row in csv.DictReader(fh):
            spectrum[int(row["coverage_depth"])] = int(row["kmer_distinct_count"])
    return distinct, spectrum, hist


def check_cardinality(reads: Path, k: int, truth: int) -> bool:
    import fastdna

    est = fastdna.estimate_cardinality(str(reads), k=k, precision=14)
    err = (est - truth) / truth * 100
    ok = abs(err) <= HLL_TOLERANCE_PCT
    print(f"  cardinality  {est:>14,.0f} vs {truth:>14,} exact   {err:+.2f}%  "
          f"(bound +/-{HLL_TOLERANCE_PCT}%)  {'OK' if ok else 'FAIL'}")
    return ok


def check_spectrum(reads: Path, k: int, truth: dict) -> bool:
    import fastdna

    try:
        est = fastdna.estimate_spectrum(str(reads), k=k)
    except Exception as exc:
        print(f"  spectrum     skipped: {exc}")
        return True
    est = {int(d): int(c) for d, c in dict(est).items()}

    # Depths 1 and 2 carry the error peak: they hold most of the distinct
    # k-mers in any real run and are where a streaming estimate is under the
    # most pressure. Deeper bins hold too few k-mers for a percentage to mean
    # much on a single-genome run.
    ok = True
    for depth in (1, 2, 3):
        if depth not in truth or truth[depth] == 0:
            continue
        got = est.get(depth, 0)
        err = (got - truth[depth]) / truth[depth] * 100
        good = abs(err) <= 10.0
        ok = ok and good
        print(f"  spectrum f{depth}  {got:>14,} vs {truth[depth]:>14,} exact   "
              f"{err:+.2f}%  (bound +/-10%)  {'OK' if good else 'FAIL'}")
    return ok


def check_genome_size(spectrum: dict, hist_csv: Path, k: int, workdir: Path) -> bool:
    from fastdna.genomescope import profile_genome

    profile = profile_genome(spectrum, k=k)
    ours = float(profile.genome_size_bp)

    lo, hi = ECOLI_PLAUSIBLE_BP
    plausible = lo <= ours <= hi
    off_ref = (ours - ECOLI_REFERENCE_BP) / ECOLI_REFERENCE_BP * 100
    print(f"  genome size  {ours:>14,.0f} bp   vs E. coli K-12 {ECOLI_REFERENCE_BP:,} bp "
          f"({off_ref:+.1f}%)  {'plausible' if plausible else 'IMPLAUSIBLE'}")
    if not profile.converged:
        print("               WARNING: the fit did not converge")

    if shutil.which("docker") is None:
        print("               (docker absent: skipped the GenomeScope2 comparison)")
        return plausible

    # GenomeScope2 wants "<depth> <count>", space separated, no header.
    gs_input = workdir / "gs_hist.txt"
    with hist_csv.open() as fh, gs_input.open("w") as out:
        for row in csv.DictReader(fh):
            out.write(f"{row['coverage_depth']} {row['kmer_distinct_count']}\n")

    outdir = workdir / "gs2_out"
    outdir.mkdir(exist_ok=True)
    proc = subprocess.run(
        ["docker", "run", "--rm", "--platform", "linux/amd64",
         "-v", f"{workdir}:/data", "-w", "/data", GENOMESCOPE_IMAGE,
         "genomescope2", "-i", gs_input.name, "-o", outdir.name, "-k", str(k), "-p", "2"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        die(f"GenomeScope2 exited {proc.returncode}:\n{proc.stderr[-2000:]}")
    match = re.search(r"len:(\d+)", proc.stdout)
    if match is None:
        die(f"could not parse GenomeScope2 output:\n{proc.stdout[-2000:]}")
    theirs = float(match.group(1))

    delta = (ours - theirs) / theirs * 100
    agrees = abs(delta) <= 5.0
    print(f"  genome size  {ours:>14,.0f} bp   vs GenomeScope2 {theirs:>14,.0f} bp   "
          f"{delta:+.2f}%  (bound +/-5%)  {'OK' if agrees else 'FAIL'}")
    return plausible and agrees


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--file", type=Path, help="FASTQ(.gz) to use instead of downloading")
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--k", type=int, default=21)
    parser.add_argument("--workdir", type=Path, default=Path.home() / ".fastdna" / "validation")
    parser.add_argument("--skip-genomescope", action="store_true")
    parser.add_argument("--json", type=Path)
    args = parser.parse_args()

    binary = REPO_ROOT / "target" / "release" / "fastdna"
    if not binary.is_file():
        die(f"{binary} not found -- run `cargo build --release` first.")

    args.workdir.mkdir(parents=True, exist_ok=True)
    if args.file is not None:
        reads = args.file.resolve()
        if not reads.is_file():
            die(f"{reads} does not exist")
    else:
        # Reuse kmc3_equivalence.py's downloader so both scripts share one
        # cached copy rather than fetching the same 97 MB twice.
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from kmc3_equivalence import fetch_reads  # noqa: E402

        reads = fetch_reads(args.url, args.workdir / "DRR002015_1.fastq.gz")

    print(f"\nexact count at k={args.k} (the ground truth for everything below)")
    truth_distinct, truth_spectrum, hist_csv = count_exact(binary, reads, args.k, args.workdir)
    print(f"  {truth_distinct:,} distinct k-mers, {len(truth_spectrum)} distinct depths")

    print("\nestimators vs that truth")
    results = [
        check_cardinality(reads, args.k, truth_distinct),
        check_spectrum(reads, args.k, truth_spectrum),
    ]
    if not args.skip_genomescope:
        results.append(check_genome_size(truth_spectrum, hist_csv, args.k, args.workdir))

    if args.json is not None:
        args.json.write_text(json.dumps({
            "k": args.k, "input": str(reads),
            "exact_distinct": truth_distinct, "all_passed": all(results),
        }, indent=2))

    if not all(results):
        die("at least one estimator missed the bound its own documentation states.")
    print("\nOK: every estimator is inside its documented bound on real data.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
